# Generated by Django 4.0.4 on 2022-05-11 18:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('valor', models.FloatField()),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime(2017, 5, 15, 9, 23, 16, 404091))),
            ],
        ),
    ]
