# Generated by Django 4.0.3 on 2022-05-16 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_carro_data_cadastro_alter_carro_img'),
    ]

    operations = [

        migrations.AlterField(
            model_name='carro',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
